---

- name: Install Java (Jenkins Dependency)
  apt:
    name: openjdk-17-jdk
    state: present 

- name: Add jenkins gpg key
  apt_key:
    url:  https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
    state: present 

- name: Add Jenkins repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present 

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start and enable Jenkins service
  service:
    name: jenkins
    state: started 
    enabled: true 

- name: Install AWS CLI(Dependency)
  apt:
    name: awscli
    state: present


